version: "3.8"

services:
  app-laravel:
    build:
      args:
        user: jhonatan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jhonatanfradepereira/laravel-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    # restart: always
    restart: unless-stopped
    networks:
      - docker-laravel

  # nginx
  nginx:
    image: nginx:alpine
    # restart: unless-stopped
    restart: always
    ports:
      - 8181:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - docker-laravel

networks:
  docker-laravel:
    driver: bridge
